[theme]

primaryColor='#1d3c34'
backgroundColor='#FFF'
secondaryBackgroundColor='#F0F4E3'
textColor='#1d3c34'

#https://fonts.google.com/icons?selected=Material+Symbols+Outlined:apps:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=apps&icon.size=24&icon.color=%235f6368